# Generated by Selenium IDE
import unittest
import time
import json
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import csv


class TestFoibrowse(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_foibrowse(self):
        self.driver.get("https://www.foi.unizg.hr/en/news")
        self.driver.set_window_size(1920, 1040)
        newsArray=[
                ["Title","Summary"]
            ]
        while True:
            newsBlock=self.driver.find_element(By.CLASS_NAME,"view-novosti")
            allNewsOnPage=newsBlock.find_elements(By.CLASS_NAME,"ostalo-naslov")
            allSummaries=newsBlock.find_elements(By.CLASS_NAME,"views-field-field-article-sazetak")
            for newsIdx in range(0,len(allNewsOnPage)):
                newsOnPage=allNewsOnPage[newsIdx]
                summaryOnPage=allSummaries[newsIdx]
                title=newsOnPage.text
                summary=summaryOnPage.text
                newsArray.append([title,summary])
                # print("--------------------------------------")
                # print(title)
                # print(summary)
                # print("--------------------------------------")
            try:
                nextPageButton=self.driver.find_element(By.CLASS_NAME,"pager-next")
                nextPageButton.click()
            except NoSuchElementException as ex:
                print("Finished looping, now exiting...")
                break

        with open('output.csv', 'w', encoding='UTF8') as fout:
            #open/create a "CSV" writer
            writer = csv.writer(fout)
            #loop through news and write each entry as a row in csv
            for row in newsArray:
                writer.writerow(row)
            fout.flush()
            fout.close()