# Generated by Selenium IDE
import unittest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestPorezni(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def tearDown(self):
        self.driver.quit()

    def test_porezni(self):
        self.driver.get("https://duznici.porezna-uprava.hr/fo/svi/1.html")
        self.driver.set_window_size(1920, 1040)
        tableOfInterest=self.driver.find_element(By.CLASS_NAME,"dataTable")
        rowsInTable=tableOfInterest.find_elements(By.TAG_NAME,"tr")
        for row in rowsInTable:
            columnsInRow=row.find_elements(By.TAG_NAME,"td")
            for column in columnsInRow:
                print(column.text)

        # assert self.driver.find_element(By.CSS_SELECTOR, ".evenRow:nth-child(2) > td:nth-child(2)").text == "MIRKO RAPIĆ"
        # self.driver.find_element(By.LINK_TEXT, ">").click()
        # self.driver.find_element(By.LINK_TEXT, ">>").click()
